// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace ConsoleApp3ML.Model
{
    public class ModelInput
    {
        [ColumnName("VIN"), LoadColumn(0)]
        public string VIN { get; set; }


        [ColumnName("year"), LoadColumn(1)]
        public float Year { get; set; }


    }
}
